name: vpipe-frontend
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - streamlit
  - matplotlib
  - numpy
  - pandas
  - pyyaml
  - seaborn
  - aiohttp
  - requests
  - pytest
  - streamlit-pydantic
  - pydantic>=1.9,<2
  - cojac>=0.9.3
  - plotly
  - pip:
      - matplotlib-venn
  