name: vpipe-frontend
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - streamlit
  - matplotlib
  - numpy
  - pandas
  - pyyaml
  - seaborn
  - aiohttp
  - requests
  - pytest
  - streamlit-pydantic
  - cojac>=0.9.3
