server:
  lapis_address: "http://88.198.54.174:80"
  cov_sprectrum_api: "https://lapis.cov-spectrum.org"

curated_variant_definitions:
  github_repo: "cbg-ethz/cowwid"
  github_branch: "master"
  github_path: "voc"