server:
  lapis_address: "https://silo.wasap.genspectrum.org/query"
  cov_spectrum_api: "https://lapis.cov-spectrum.org"

curated_variant_definitions:
  # Full GitHub repository URL (e.g., https://github.com/cbg-ethz/cowwid)
  github_url: "https://github.com/cbg-ethz/cowwid/tree/master/voc"