name: v-pipe-scout-app
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - streamlit=1.49.0
  - matplotlib
  - numpy
  - pandas=2.2.3
  - pyyaml
  - aiohttp
  - requests
  - pytest
  - pytest-asyncio
  - pytest-mock
  - streamlit-pydantic
  - pydantic>=1.9,<2
  - plotly>=6.2.0
  - pip
  - celery==5.3.6
  - pip:
      - matplotlib-venn
      - redis==5.0.1
      - streamlit-autorefresh
      - st-theme
