name: v-pipe-scout-worker
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python and lollipop dependencies
  - python=3.10
  - numpy>=1.23
  - scipy>=1.9
  - pandas>=1.5
  - tqdm>=4.64
  - threadpoolctl>=3.5.0
  - ruamel.yaml>=0.15.80
  - strictyaml>=1.7
  - zstandard>=0.20
  - click>=8.0
  - click-option-group>=0.5
  - lollipop>=0.5.3
  
  # CLI tools - for tallymut assembly
  - xsv=0.13.0
  - gawk=5.3.1
  
  # other python
  - pyyaml

  # Optional: for your workflow/testing
  - pytest
  - pytest-mock # Added pytest-mock for the mocker fixture

  # Celery worker dependencies
  - celery=5.3.6
  
  - pip
  - pip:
      - redis==5.0.1