name: Deploy to Production

on:
  release: 
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          port: ${{ secrets.PRODUCTION_SSH_PORT || '22' }}
          script: |
            cd /opt/v-pipe-scout
            git config --global --add safe.directory /opt/v-pipe-scout
            git pull origin main || exit 1
            echo "Pulled latest commit: $(git rev-parse HEAD)"
            docker compose down
            docker compose up -d --build
            sleep 9
            if curl -f -s -o /dev/null "${{ secrets.PRODUCTION_URL }}"; then
              echo "Deployment successful!"
            else
              echo "Deployment failed - health check failed"
              exit 1
            fi