name: Docker CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_run_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run Docker container using Makefile
        run: make docker

      - name: Check if Docker container is running
        run: |
          sleep 10 # Give the container a moment to start
          docker ps
          if [ $(docker ps -q -f "ancestor=v-pipe-scout") ]; then
            echo "Docker container is running."
          else
            echo "Docker container failed to start."
            docker logs $(docker ps -aq -f "ancestor=v-pipe-scout" | head -n 1)
            exit 1
          fi
      
      - name: Stop and remove Docker container
        if: always() # Ensure this step runs even if previous steps fail
        run: |
          CONTAINER_ID=$(docker ps -aq -f "ancestor=v-pipe-scout")
          if [ -n "$CONTAINER_ID" ]; then
            docker stop $CONTAINER_ID
            docker rm $CONTAINER_ID
          fi